name: Generate & Publish Post

on:
  schedule:
    # Runs every day at 15:05 UTC (7:05 AM PT). Adjust as you like.
    - cron: '5 15 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate post
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python generate_posts.py --once

      - name: Commit new post
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add _posts/*.md || true
          git commit -m "chore: add new post [skip ci]" || echo "No changes"
          git push

